[package]
name = "nr-adf-tools"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.91"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
nr-adf-lib = { path = "../nr-adf-lib" }
